* General Information

Ideas possibly requiring interaction with all project members.

** Color Palette

*** TODO Decide on a color palette

**** Ideas

+ https://hookagency.com/website-color-schemes/ palettes 8 and 9

* Pages

** Font

Base font: [[https://fonts.google.com/specimen/Work+Sans?preview.size=25&sidebar.open&selection.family=Work+Sans][Work Sans by Wei Huang]]

** Pages Overview

*** General

+ Four pages: Home Page, About, Donate, FAQ
+ Also sign on? *Link to sign on and signup to be provided by Front
  end*
+ Standard header and footer?
+ Preprocessor
 + They aren't teaching LESS any longer, but they still use SASS in
   React, will it be useful for us to learn it a little early?
 + How difficult is it to install a preprocessor on Windows?
  + And if we are going to have to do it eventually anyway, might we
    just as well figure it out now regardless?
  + Perhaps after finishing bulk of work i.e. Wednesday or Thursday?
 + Interaction with other development tools e.g, Live Server, gint*?*

*** Project structure

*/*
+ *index.html* Home page
+ *about.html* About page
+ *donate.html* Donate page
+ *faq.html* FAQ page
+ *footer.html* Template footer
+ *header.html* Template header
+ *assets/* images
+ *css/* css files
 + *replate.css* common css for all page
 + */page-name/.css* css pages for each page

*** Donate Page

*** FAQ

** Wireframes

*** Header

#+BEGIN_SRC ditaa :file org-header-wireflame.png
 +-------------------------------------------------------+
 |                                                       |
 |  +---+  Background image        +------------------+  |
 |  | R |   of pans of leftover    | Login   Sign up  |  |
 |  +---+    food                  |                  |  |
 |                                 +------------------+  |
 |                                                       |
 |          Home  About  FAQ  Donate                     |
 |                                                       |
 +-------------------------------------------------------+
#+END_SRC

*** Footer

*** Donate Page

*** FAQ
